version: "3.9"

services:
  db:
    #image: mongo:7
    image: mongo:4.4.18 # Raspberry Pi 4 does not support MongoDB 7, so we use an older version
    container_name: ingestor-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /mnt/wdred/ingester_data:/data/db
  ingestor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dxspider-ingestor
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
